name = "OptiTest"
uuid = "8e73529a-8039-44f2-9503-feb13149ead0"
authors = ["sandyspiers <sandy.spiers@curtin.edu.au> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
